### ISSUE TITLE
ALTO overview presentation at CERN on April 27

### ISSUE THREAD

**Issue by giralt** [ietf-wg-alto/wg-materials#16]

**Comment by giralt** [comment]
Current presentation draft: https://docs.google.com/presentation/d/15i4fYQzuDLF6J6JoD5y8rNDglsJNjoLq-cpn0eiDgLg/edit?usp=sharing

**Comment by fno2010** [comment]
The full video recording for the DOMA meeting is available: https://indico.cern.ch/event/1148142/attachments/2433136/4166779/GMT20220427-140337_Recording_1920x1080.mp4
