### ISSUE TITLE
Adoption call for draft-zhang-alto-oam-yang

### ISSUE THREAD

**Issue by giralt** [ietf-wg-alto/wg-materials#8]

**Comment by fno2010** [comment]
- [x] [draft-ietf-alto-oam-yang-00](https://datatracker.ietf.org/doc/draft-ietf-alto-oam-yang/) has been submitted for WG adoption.
- [x] The repo [ietf-wg-alto/draft-ietf-alto-oam-yang](https://github.com/ietf-wg-alto/draft-ietf-alto-oam-yang) has been created to track the progress of this work.
